name: Auto Merge PR if Sonar Checks Pass

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'open'
    steps:
      - name: Wait for required checks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            const checks = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: pr.head.sha,
            });

            const requiredChecks = [
              "SonarCloud Code Analysis",
              "SonarQube Analysis / SonarQube Scan (pull_request)"
            ];

            let allSuccess = true;
            for (const checkName of requiredChecks) {
              const check = checks.data.check_runs.find(c => c.name === checkName);
              if (!check || check.conclusion !== "success") {
                allSuccess = false;
                break;
              }
            }

            if (allSuccess) {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number: pr.number,
                merge_method: "merge"
              });
              console.log("PR merged automatically!");
            } else {
              console.log("Not all Sonar checks passed.");
            }
